### ISSUE TITLE
Bag Books need to bag copyIds

### ISSUE THREAD

**Issue by richardsoriano** [richardsoriano/book-beats#39]
- [x] Bag Form. Modify bag - display category, books only.
- [x] Bags. Add columns, titles, copyIds.
- [x] #40
- [x] Check if copyId is not already in another Bag. Prevent user from adding it. // Not needed
- [x] Create ServerSide Hashmap of copyIds/BagIds. ArrayOfBaggedCopyIds. // Not needed.

**Comment by DanielekPark** [comment]
Bag Form, look at src/pages/books/create/index.js ?

**Comment by richardsoriano** [comment]
I fixed this in my last PR. I should've ties these issues to the PR.

**Comment by DanielekPark** [comment]
> I fixed this in my last PR. I should've ties these issues to the PR.

Got it
